/**
 * Tour buffer — sessionStorage-backed write queue for the anonymous
 * /onboard flow (Plan A).
 *
 * During the pre-signup tour, every write the tour would normally POST
 * (profile creation, dependent creation, conditions, medications, todos)
 * is captured here instead. On signup, the flush step (Phase 3) reads
 * this buffer in order and replays each write against the now-authed
 * backend.
 *
 * Keep this module dependency-free (no React, no fetch) so the flush
 * logic can import it from anywhere — AuthModal callback, useEffect on
 * /chat landing, or a standalone test harness.
 */

const BUFFER_KEY = "elena_tour_buffer";

export interface BufferedProfile {
  first_name?: string;
  last_name?: string;
  date_of_birth?: string;
  zip_code?: string;
  home_address?: string;
}

export interface BufferedDependent {
  first_name: string;
  last_name?: string;
  date_of_birth?: string;
  zip_code?: string;
  label?: string;
  relationship: string;
  /** True for the PRIMARY dependent the user explicitly set up for
   *  (setup-for phase). False for "silent" other-family-member profiles
   *  we auto-create from careSelections. The flush step switches profile
   *  to the primary dependent and leaves the silent ones un-switched. */
  is_primary_dependent: boolean;
}

export interface BufferedCondition {
  name: string;
  status?: string;
  diagnosed_date?: string;
  notes?: string;
  /** When true, save on the dependent profile (if one was created).
   *  Otherwise save on the primary user's profile. */
  on_dependent?: boolean;
}

export interface BufferedMedication {
  name: string;
  /** Condition this med is for — populated from the template's conditionName
   *  so the medication row has context when the agent reads it later. */
  indication?: string;
  dosage_strength?: string;
  frequency?: string;
  on_dependent?: boolean;
}

export interface BufferedTodo {
  title: string;
  subtitle?: string;
  category?: string;
  frequency?: string;
  due_date?: string;
  book_message?: string;
  on_dependent?: boolean;
}

export interface TourBuffer {
  /** Primary user's profile data (what the old completeOnboarding POSTed). */
  profile?: BufferedProfile;
  /** Dependents created in setup-for (primary + silent others). */
  dependents: BufferedDependent[];
  /** Condition / medication saves that happened mid-tour. */
  conditions: BufferedCondition[];
  medications: BufferedMedication[];
  /** Care-plan / validation todos generated by the tour. */
  todos: BufferedTodo[];
  /** The seed action string the user picked on elena-plan. Set by
   *  finishTour just before opening AuthModal. */
  seed_query?: string;
  /** Tracks when each entry was enqueued so flush can replay in order. */
  created_at?: string;
}

function emptyBuffer(): TourBuffer {
  return {
    dependents: [],
    conditions: [],
    medications: [],
    todos: [],
  };
}

export function readTourBuffer(): TourBuffer {
  if (typeof window === "undefined") return emptyBuffer();
  try {
    const raw = sessionStorage.getItem(BUFFER_KEY);
    if (!raw) return emptyBuffer();
    const parsed = JSON.parse(raw) as Partial<TourBuffer>;
    return {
      profile: parsed.profile,
      dependents: parsed.dependents || [],
      conditions: parsed.conditions || [],
      medications: parsed.medications || [],
      todos: parsed.todos || [],
      seed_query: parsed.seed_query,
      created_at: parsed.created_at,
    };
  } catch {
    return emptyBuffer();
  }
}

function writeTourBuffer(buf: TourBuffer) {
  if (typeof window === "undefined") return;
  try {
    sessionStorage.setItem(BUFFER_KEY, JSON.stringify({
      ...buf,
      created_at: buf.created_at || new Date().toISOString(),
    }));
  } catch {}
}

export function clearTourBuffer() {
  if (typeof window === "undefined") return;
  try { sessionStorage.removeItem(BUFFER_KEY); } catch {}
}

/** Update or set the primary profile entry. */
export function setBufferedProfile(profile: BufferedProfile) {
  const buf = readTourBuffer();
  buf.profile = { ...buf.profile, ...profile };
  writeTourBuffer(buf);
}

/** Add a dependent (primary or silent). Dedupes by first_name+relationship
 *  so double-calls (StrictMode, retries) don't accumulate duplicates. */
export function addBufferedDependent(dep: BufferedDependent) {
  const buf = readTourBuffer();
  const key = `${(dep.first_name || "").toLowerCase()}|${(dep.relationship || "").toLowerCase()}`;
  const exists = buf.dependents.some(
    (d) => `${(d.first_name || "").toLowerCase()}|${(d.relationship || "").toLowerCase()}` === key,
  );
  if (!exists) {
    buf.dependents.push(dep);
    writeTourBuffer(buf);
  }
}

export function addBufferedCondition(c: BufferedCondition) {
  const buf = readTourBuffer();
  buf.conditions.push(c);
  writeTourBuffer(buf);
}

export function addBufferedMedication(m: BufferedMedication) {
  const buf = readTourBuffer();
  // Dedupe by name so the med selector + custom-meds paths don't both
  // push the same med.
  if (!buf.medications.some((x) => x.name.toLowerCase() === m.name.toLowerCase())) {
    buf.medications.push(m);
    writeTourBuffer(buf);
  }
}

export function addBufferedTodo(t: BufferedTodo) {
  const buf = readTourBuffer();
  if (!buf.todos.some((x) => x.title.toLowerCase() === t.title.toLowerCase())) {
    buf.todos.push(t);
    writeTourBuffer(buf);
  }
}

export function setBufferedSeedQuery(q: string) {
  const buf = readTourBuffer();
  buf.seed_query = q;
  writeTourBuffer(buf);
}

/**
 * Post-signup flush: replay every buffered write against the authed
 * backend, in order. Called from /onboard's AuthModal onAuthed callback
 * after supabase confirms the session. Keep this resilient — if any
 * single POST fails, the others still run, and we still land the user
 * in /chat where they can recover via the profile popover.
 *
 * The imports are dynamic so this module stays dependency-free at
 * module-load time (sessionStorage access only). apiFetch / auth-context
 * are only needed when flushing.
 */
export interface FlushResult {
  profile_saved: boolean;
  dependents_created: number;
  primary_dependent_id: string | null;
  prewarmed_session_id: string | null;
  errors: string[];
  /** Per-stage wall time in ms. Keys are FlushStage values. */
  stage_timings_ms?: Record<string, number>;
  /** Total flush duration in ms. */
  duration_total_ms?: number;
}

export interface StorageLike {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
  removeItem?(key: string): void;
}

/** Progress stages the flush reports as it runs. Consumers show these
 *  as labels on a loading screen so the user sees something happening. */
export type FlushStage =
  | "saving_profile"
  | "creating_family"
  | "switching_profile"
  | "saving_health_data"
  | "loading_chat"
  | "done";

export async function flushTourBuffer(opts: {
  switchProfile: (id: string) => Promise<void> | void;
  refreshProfiles: () => Promise<void> | void;
  /** Auth-context's completeOnboarding. Used instead of raw apiFetch so
   *  the flush flips needsOnboarding/onboardingJustCompleted in React
   *  state. Without this, /chat keeps re-mounting the tour on every
   *  visit because needsOnboarding stays true. */
  completeOnboarding: (data: {
    first_name?: string;
    last_name?: string;
    date_of_birth?: string;
    home_address?: string;
  }) => Promise<void>;
  /** Called as each flush stage starts so the loading screen can show
   *  a running label + progress bar. */
  onProgress?: (stage: FlushStage, percent: number) => void;
}): Promise<FlushResult> {
  const buf = readTourBuffer();
  const { apiFetch } = await import("./apiFetch");
  const localStore =
    typeof window !== "undefined" ? localStorage : undefined;
  const sessionStore =
    typeof window !== "undefined" ? sessionStorage : undefined;
  return flushBufferedTourData(buf, {
    ...opts,
    apiFetch,
    localStorage: localStore,
    sessionStorage: sessionStore,
    clearBuffer: clearTourBuffer,
  });
}

export async function flushBufferedTourData(
  buf: TourBuffer,
  opts: {
    apiFetch: (
      path: string,
      options?: RequestInit,
    ) => Promise<Response>;
    switchProfile: (id: string) => Promise<void> | void;
    refreshProfiles: () => Promise<void> | void;
    completeOnboarding: (data: {
      first_name?: string;
      last_name?: string;
      date_of_birth?: string;
      home_address?: string;
    }) => Promise<void>;
    onProgress?: (stage: FlushStage, percent: number) => void;
    localStorage?: StorageLike;
    sessionStorage?: StorageLike;
    clearBuffer?: () => void;
  },
): Promise<FlushResult> {
  const result: FlushResult = {
    profile_saved: false,
    dependents_created: 0,
    primary_dependent_id: null,
    prewarmed_session_id: null,
    errors: [],
  };
  if (!buf.profile && buf.dependents.length === 0 && !buf.seed_query) {
    // Nothing buffered — user probably came through OAuth without the
    // anonymous tour (e.g. direct signup on /login). Nothing to flush.
    console.log("[flush] skipped — empty buffer");
    return result;
  }

  // Start-of-flush snapshot. If a user reports "my meds didn't save" or
  // "my dependent is missing," the ground truth is what was in the
  // buffer right before we replayed it — not what the tour "should have"
  // captured. Logging this at start makes root-cause possible from the
  // console without having to reconstruct state.
  console.log("[flush] start", {
    has_profile: !!buf.profile,
    profile_has_first_name: !!buf.profile?.first_name,
    profile_has_dob: !!buf.profile?.date_of_birth,
    profile_has_zip: !!buf.profile?.zip_code,
    dependents: buf.dependents.length,
    primary_dependent: buf.dependents.find((d) => d.is_primary_dependent)?.first_name || null,
    conditions: buf.conditions.length,
    medications: buf.medications.length,
    todos: buf.todos.length,
    seed_preview: buf.seed_query?.slice(0, 60) ?? null,
  });

  const flushStartedAt = typeof performance !== "undefined" ? performance.now() : Date.now();
  const stageTimings: Record<string, number> = {};
  let currentStage: FlushStage = "saving_profile";
  let currentStageStart = flushStartedAt;

  const report = (stage: FlushStage, percent: number) => {
    try { opts.onProgress?.(stage, percent); } catch {}
    const now = typeof performance !== "undefined" ? performance.now() : Date.now();
    if (currentStage !== stage) {
      const elapsed = Math.round(now - currentStageStart);
      stageTimings[currentStage] = (stageTimings[currentStage] || 0) + elapsed;
      console.log(`[flush] stage done: ${currentStage} (${elapsed}ms) → ${stage}`);
      currentStage = stage;
      currentStageStart = now;
    }
  };

  // Stage 1 — create the primary profile first, then create any
  // dependents. This ordering is deliberate: if the backend ever
  // requires a primary profile row / active-profile context before it
  // can safely create managed profiles, running these in parallel can
  // strand the signup in a "dependent exists, me profile missing"
  // state. The app hit this class of bug already; web should not take
  // the same risk for a few hundred ms of latency savings.
  report("saving_profile", 10);
  if (buf.profile) {
    try {
      await opts.completeOnboarding({
        first_name: buf.profile.first_name,
        last_name: buf.profile.last_name,
        date_of_birth: buf.profile.date_of_birth,
        home_address: buf.profile.zip_code || buf.profile.home_address,
      });
      result.profile_saved = true;
    } catch (e) {
      result.errors.push(`completeOnboarding threw: ${(e as Error).message}`);
    }
  }

  const createDependents = async () => {
    // Primary dependent first in the response order so we can pick
    // its id out synchronously after Promise.all.
    const primary = buf.dependents.find((d) => d.is_primary_dependent);
    const secondaries = buf.dependents.filter((d) => !d.is_primary_dependent);
    const ordered = primary ? [primary, ...secondaries] : secondaries;
    const responses = await Promise.all(
      ordered.map(async (dep) => {
        try {
          const body: Record<string, string> = {
            first_name: dep.first_name,
            last_name: dep.last_name || "",
            relationship: dep.relationship,
          };
          if (dep.label) body.label = dep.label;
          if (dep.date_of_birth) body.date_of_birth = dep.date_of_birth;
          if (dep.zip_code) body.zip_code = dep.zip_code;
          const res = await opts.apiFetch("/profiles", {
            method: "POST",
            body: JSON.stringify(body),
          });
          if (!res.ok) {
            result.errors.push(`dependent ${dep.first_name} POST ${res.status}`);
            return null;
          }
          const created = await res.json();
          const newId: string | null = created?.id || created?.profile_id || null;
          if (newId) {
            result.dependents_created++;
            if (dep.is_primary_dependent) result.primary_dependent_id = newId;
          }
          return newId;
        } catch (e) {
          result.errors.push(`dependent ${dep.first_name} threw: ${(e as Error).message}`);
          return null;
        }
      }),
    );
    return responses;
  };

  await createDependents();
  report("creating_family", 40);

  // Stage 2 — refresh profiles + switch to primary dependent (if any).
  // Both are local-state operations or upserts; fast.
  try { await opts.refreshProfiles(); } catch {}
  console.log("[flush] stage 2: primary_dependent_id =", result.primary_dependent_id, "dependents_created =", result.dependents_created, "errors =", result.errors);
  if (result.primary_dependent_id) {
    try {
      await opts.switchProfile(result.primary_dependent_id);
      console.log("[flush] switchProfile succeeded →", result.primary_dependent_id);
    } catch (e) {
      result.errors.push(`switchProfile threw: ${(e as Error).message}`);
      console.error("[flush] switchProfile threw:", e);
    }
  } else {
    console.warn("[flush] no primary_dependent_id — NOT calling switchProfile. User will land on primary (main user) profile. Check that the managed dependent POST succeeded.");
  }
  report("switching_profile", 55);

  // Stage 3 — resolve activeProfileId, then fire health-data writes
  // AND chat welcome pre-warm in parallel. The welcome pre-warm is the
  // big latency win: under the old flow chat-area fetched welcome only
  // after /chat mounted, producing a visible blank while the seed
  // message waited. Kicking welcome off during the flush means /chat
  // lands on an already-provisioned session and the seed fires
  // immediately.
  //
  // IMPORTANT: prefer result.primary_dependent_id over /auth/me's
  // profile_id. switchProfile() in auth-context updates client state
  // synchronously but fires the `/profiles/{id}/switch` PUT to the
  // backend as fire-and-forget. If we call /auth/me here before that
  // PUT has landed, we get the stale server-side active profile (the
  // primary / main user) and write every condition / med / todo to
  // the WRONG profile. Using primary_dependent_id directly avoids the
  // race entirely: if we just created a managed profile and know its
  // id, that's authoritatively where the tour's captured data belongs.
  // Only fall back to /auth/me for the self-setup case (no managed
  // profile created this session).
  let activeProfileId: string | null = result.primary_dependent_id;
  if (!activeProfileId) {
    try {
      const meRes = await opts.apiFetch("/auth/me");
      if (meRes.ok) {
        const me = await meRes.json();
        activeProfileId = me?.profile_id || null;
      }
    } catch (e) {
      result.errors.push(`/auth/me threw: ${(e as Error).message}`);
    }
  }
  console.log("[flush] stage 3: activeProfileId =", activeProfileId, "source =", result.primary_dependent_id ? "primary_dependent_id" : "/auth/me");

  report("saving_health_data", 65);
  const healthAndWelcomeTasks: Promise<unknown>[] = [];

  if (activeProfileId) {
    // Conditions — now parallel (was sequential in for-loop previously).
    for (const c of buf.conditions) {
      healthAndWelcomeTasks.push(
        (async () => {
          try {
            const body: Record<string, string> = { name: c.name };
            if (c.status) body.status = c.status;
            if (c.diagnosed_date) body.diagnosed_date = c.diagnosed_date;
            if (c.notes) body.notes = c.notes;
            const res = await opts.apiFetch(`/profile/${activeProfileId}/conditions/add`, {
              method: "POST",
              body: JSON.stringify(body),
            });
            if (!res.ok) result.errors.push(`condition ${c.name} POST ${res.status}`);
          } catch (e) {
            result.errors.push(`condition ${c.name} threw: ${(e as Error).message}`);
          }
        })(),
      );
    }
    for (const m of buf.medications) {
      healthAndWelcomeTasks.push(
        (async () => {
          try {
            const body: Record<string, string> = { name: m.name };
            if (m.indication) body.indication = m.indication;
            if (m.dosage_strength) body.dosage_strength = m.dosage_strength;
            if (m.frequency) body.frequency = m.frequency;
            const res = await opts.apiFetch(`/profile/${activeProfileId}/medications/add`, {
              method: "POST",
              body: JSON.stringify(body),
            });
            if (!res.ok) result.errors.push(`med ${m.name} POST ${res.status}`);
          } catch (e) {
            result.errors.push(`med ${m.name} threw: ${(e as Error).message}`);
          }
        })(),
      );
    }
    for (const t of buf.todos) {
      healthAndWelcomeTasks.push(
        (async () => {
          try {
            const body: Record<string, string> = { title: t.title };
            if (t.subtitle) body.subtitle = t.subtitle;
            if (t.category) body.category = t.category;
            if (t.frequency) body.frequency = t.frequency;
            if (t.due_date) body.due_date = t.due_date;
            if (t.book_message) body.book_message = t.book_message;
            const res = await opts.apiFetch("/todos", {
              method: "POST",
              body: JSON.stringify(body),
            });
            if (!res.ok) result.errors.push(`todo ${t.title} POST ${res.status}`);
          } catch (e) {
            result.errors.push(`todo ${t.title} threw: ${(e as Error).message}`);
          }
        })(),
      );
    }
  } else if (buf.conditions.length > 0 || buf.medications.length > 0 || buf.todos.length > 0) {
    result.errors.push(
      `health_data_skipped: no active_profile_id (conditions=${buf.conditions.length}, meds=${buf.medications.length}, todos=${buf.todos.length})`,
    );
  }

  // Pre-warm chat — fires POST /chat/welcome now, races with health
  // writes. The returned session_id is stashed in sessionStorage so
  // /chat picks it up as activeSessionId on mount and skips its own
  // welcome fetch. Silent=true because the real welcome UI shows in
  // chat-area; we just want the session to exist + the cached messages
  // primed.
  healthAndWelcomeTasks.push(
    (async () => {
      try {
        const res = await opts.apiFetch("/chat/welcome", {
          method: "POST",
          body: JSON.stringify({}),
        });
        if (!res.ok) return;
        const data = await res.json();
        const sid: string | null = data?.session_id || null;
        if (sid) {
          result.prewarmed_session_id = sid;
          try { opts.sessionStorage?.setItem("elena_active_session_id", sid); } catch {}
          // Also seed the welcome-message cache chat-area reads so it
          // doesn't re-fetch on mount. Key matches chat-area's convention.
          try {
            if (data.heading || data.message) {
              opts.sessionStorage?.setItem(
                "elena_prewarmed_welcome",
                JSON.stringify({ session_id: sid, heading: data.heading, message: data.message, suggestions: data.suggestions || [] }),
              );
            }
          } catch {}
        }
      } catch (e) {
        result.errors.push(`welcome prewarm threw: ${(e as Error).message}`);
      }
    })(),
  );

  await Promise.all(healthAndWelcomeTasks);
  report("loading_chat", 90);

  // 5) Tour-resume handoff. Tour state was persisted with phase="elena-plan"
  //    when the user clicked Continue (since we short-circuited before
  //    the phase transition). Update the stored phase to "joyride" so
  //    /chat's tour mount resumes at the "This is your profile" spotlight
  //    — it orients the user before opening the profile walkthrough cards.
  //    The joyride's TOUR_END handler advances to phase="profile" with
  //    profileStep=0, so from the user's POV the flow is:
  //       (anon) elena-plan Continue → signup → (authed) /chat
  //       → "This is your profile" spotlight → Health / Visits / Insurance
  //       / Family cards → seed sends into chat.
  //    The static snapshot's "joyride → profile" fallback (in tourSnapshot
  //    useMemo) only applies when the controls instance can't survive the
  //    transition. Under Plan A the tour remounts on /chat, so the joyride
  //    instance is fresh and the phase effect starts it via controls.start().
  //
  //    Also preserve the seeded-actions key in sessionStorage so the
  //    tour's existing finishTour logic (end of profile walkthrough)
  //    writes localStorage.elena_pending_query at the *natural* moment
  //    — AFTER the user finishes the walkthrough cards. If we wrote
  //    the seed here instead, chat-area's auto-send effect would fire
  //    the seed while the walkthrough overlay was still up, producing
  //    an agent response underneath the tour cards. The authed flow's
  //    timing is "seed fires on finishTour" — we preserve that.
  if (opts.localStorage || opts.sessionStorage) {
    try {
      // Tour state moved to localStorage for cross-tab durability;
      // fall back to sessionStorage for any in-flight sessions that
      // still have old keys.
      const raw =
        opts.localStorage?.getItem("elena_tour_state") ||
        opts.sessionStorage?.getItem("elena_tour_state");
      if (raw) {
        const state = JSON.parse(raw);
        state.phase = "joyride";
        state.profileStep = 0;
        opts.localStorage?.setItem("elena_tour_state", JSON.stringify(state));
      }
    } catch {}
    // Ensure finishTour (at the end of profile walkthrough) has an
    // elena_tour_seeded_actions payload to read. The tour's elena-plan
    // Continue handler wrote this already in the authed path; make sure
    // it's still there for anon path (it IS — advanceFromElenaPlan
    // writes the key before the anon short-circuit). Nothing else to
    // do here, documenting for clarity.
  }

  // Clear the tour buffer after a successful or partial flush — anything
  // that failed is recoverable via the profile popover, and keeping the
  // buffer around would replay on a later tour attempt. elena_tour_state
  // + elena_tour_seeded_actions stay (finishTour consumes them at the
  // end of the resumed profile walkthrough).
  try { opts.clearBuffer?.(); } catch {}
  report("done", 100);

  // End-of-flush summary. Mirrors what the loading-screen progress bar
  // showed the user, but with real error strings + timings so a support
  // engineer debugging a failed signup has the full story in one log
  // line. Stage timings roll up the per-stage elapsed times; sum should
  // approximate duration_total_ms.
  const flushEndedAt = typeof performance !== "undefined" ? performance.now() : Date.now();
  const stageElapsed = Math.round(flushEndedAt - currentStageStart);
  stageTimings[currentStage] = (stageTimings[currentStage] || 0) + stageElapsed;
  const duration_total_ms = Math.round(flushEndedAt - flushStartedAt);
  result.stage_timings_ms = stageTimings;
  result.duration_total_ms = duration_total_ms;
  console.log("[flush] done", {
    duration_total_ms,
    stage_timings_ms: stageTimings,
    profile_saved: result.profile_saved,
    dependents_created: result.dependents_created,
    primary_dependent_id: result.primary_dependent_id,
    prewarmed_session_id: result.prewarmed_session_id,
    error_count: result.errors.length,
    errors: result.errors,
  });
  return result;
}
