/**
 * Tour buffer — sessionStorage-backed write queue for the anonymous
 * /onboard flow (Plan A).
 *
 * During the pre-signup tour, every write the tour would normally POST
 * (profile creation, dependent creation, conditions, medications, todos)
 * is captured here instead. On signup, the flush step (Phase 3) reads
 * this buffer in order and replays each write against the now-authed
 * backend.
 *
 * Keep this module dependency-free (no React, no fetch) so the flush
 * logic can import it from anywhere — AuthModal callback, useEffect on
 * /chat landing, or a standalone test harness.
 */

const BUFFER_KEY = "elena_tour_buffer";

export interface BufferedProfile {
  first_name?: string;
  last_name?: string;
  date_of_birth?: string;
  zip_code?: string;
  home_address?: string;
}

export interface BufferedDependent {
  first_name: string;
  last_name?: string;
  date_of_birth?: string;
  zip_code?: string;
  label?: string;
  relationship: string;
  /** True for the PRIMARY dependent the user explicitly set up for
   *  (setup-for phase). False for "silent" other-family-member profiles
   *  we auto-create from careSelections. The flush step switches profile
   *  to the primary dependent and leaves the silent ones un-switched. */
  is_primary_dependent: boolean;
}

export interface BufferedCondition {
  name: string;
  status?: string;
  diagnosed_date?: string;
  notes?: string;
  /** When true, save on the dependent profile (if one was created).
   *  Otherwise save on the primary user's profile. */
  on_dependent?: boolean;
}

export interface BufferedMedication {
  name: string;
  /** Condition this med is for — populated from the template's conditionName
   *  so the medication row has context when the agent reads it later. */
  indication?: string;
  dosage_strength?: string;
  frequency?: string;
  on_dependent?: boolean;
}

export interface BufferedTodo {
  title: string;
  subtitle?: string;
  category?: string;
  frequency?: string;
  due_date?: string;
  book_message?: string;
  on_dependent?: boolean;
}

export interface TourBuffer {
  /** Primary user's profile data (what the old completeOnboarding POSTed). */
  profile?: BufferedProfile;
  /** Dependents created in setup-for (primary + silent others). */
  dependents: BufferedDependent[];
  /** Condition / medication saves that happened mid-tour. */
  conditions: BufferedCondition[];
  medications: BufferedMedication[];
  /** Care-plan / validation todos generated by the tour. */
  todos: BufferedTodo[];
  /** The seed action string the user picked on elena-plan. Set by
   *  finishTour just before opening AuthModal. */
  seed_query?: string;
  /** Tracks when each entry was enqueued so flush can replay in order. */
  created_at?: string;
}

function emptyBuffer(): TourBuffer {
  return {
    dependents: [],
    conditions: [],
    medications: [],
    todos: [],
  };
}

export function readTourBuffer(): TourBuffer {
  if (typeof window === "undefined") return emptyBuffer();
  try {
    const raw = sessionStorage.getItem(BUFFER_KEY);
    if (!raw) return emptyBuffer();
    const parsed = JSON.parse(raw) as Partial<TourBuffer>;
    return {
      profile: parsed.profile,
      dependents: parsed.dependents || [],
      conditions: parsed.conditions || [],
      medications: parsed.medications || [],
      todos: parsed.todos || [],
      seed_query: parsed.seed_query,
      created_at: parsed.created_at,
    };
  } catch {
    return emptyBuffer();
  }
}

function writeTourBuffer(buf: TourBuffer) {
  if (typeof window === "undefined") return;
  try {
    sessionStorage.setItem(BUFFER_KEY, JSON.stringify({
      ...buf,
      created_at: buf.created_at || new Date().toISOString(),
    }));
  } catch {}
}

export function clearTourBuffer() {
  if (typeof window === "undefined") return;
  try { sessionStorage.removeItem(BUFFER_KEY); } catch {}
}

/** Update or set the primary profile entry. */
export function setBufferedProfile(profile: BufferedProfile) {
  const buf = readTourBuffer();
  buf.profile = { ...buf.profile, ...profile };
  writeTourBuffer(buf);
}

/** Add a dependent (primary or silent). Dedupes by first_name+relationship
 *  so double-calls (StrictMode, retries) don't accumulate duplicates. */
export function addBufferedDependent(dep: BufferedDependent) {
  const buf = readTourBuffer();
  const key = `${(dep.first_name || "").toLowerCase()}|${(dep.relationship || "").toLowerCase()}`;
  const exists = buf.dependents.some(
    (d) => `${(d.first_name || "").toLowerCase()}|${(d.relationship || "").toLowerCase()}` === key,
  );
  if (!exists) {
    buf.dependents.push(dep);
    writeTourBuffer(buf);
  }
}

export function addBufferedCondition(c: BufferedCondition) {
  const buf = readTourBuffer();
  buf.conditions.push(c);
  writeTourBuffer(buf);
}

export function addBufferedMedication(m: BufferedMedication) {
  const buf = readTourBuffer();
  // Dedupe by name so the med selector + custom-meds paths don't both
  // push the same med.
  if (!buf.medications.some((x) => x.name.toLowerCase() === m.name.toLowerCase())) {
    buf.medications.push(m);
    writeTourBuffer(buf);
  }
}

export function addBufferedTodo(t: BufferedTodo) {
  const buf = readTourBuffer();
  if (!buf.todos.some((x) => x.title.toLowerCase() === t.title.toLowerCase())) {
    buf.todos.push(t);
    writeTourBuffer(buf);
  }
}

export function setBufferedSeedQuery(q: string) {
  const buf = readTourBuffer();
  buf.seed_query = q;
  writeTourBuffer(buf);
}

/**
 * Post-signup flush: replay every buffered write against the authed
 * backend, in order. Called from /onboard's AuthModal onAuthed callback
 * after supabase confirms the session. Keep this resilient — if any
 * single POST fails, the others still run, and we still land the user
 * in /chat where they can recover via the profile popover.
 *
 * The imports are dynamic so this module stays dependency-free at
 * module-load time (sessionStorage access only). apiFetch / auth-context
 * are only needed when flushing.
 */
export interface FlushResult {
  profile_saved: boolean;
  dependents_created: number;
  primary_dependent_id: string | null;
  errors: string[];
}

export async function flushTourBuffer(opts: {
  switchProfile: (id: string) => Promise<void> | void;
  refreshProfiles: () => Promise<void> | void;
  /** Auth-context's completeOnboarding. Used instead of raw apiFetch so
   *  the flush flips needsOnboarding/onboardingJustCompleted in React
   *  state. Without this, /chat keeps re-mounting the tour on every
   *  visit because needsOnboarding stays true. */
  completeOnboarding: (data: {
    first_name?: string;
    last_name?: string;
    date_of_birth?: string;
    home_address?: string;
  }) => Promise<void>;
}): Promise<FlushResult> {
  const result: FlushResult = {
    profile_saved: false,
    dependents_created: 0,
    primary_dependent_id: null,
    errors: [],
  };
  const buf = readTourBuffer();
  if (!buf.profile && buf.dependents.length === 0 && !buf.seed_query) {
    // Nothing buffered — user probably came through OAuth without the
    // anonymous tour (e.g. direct signup on /login). Nothing to flush.
    return result;
  }

  const { apiFetch } = await import("./apiFetch");

  // 1) Primary profile (user_profiles row). Go through completeOnboarding
  //    rather than raw apiFetch so auth-context state updates (profileId,
  //    profileData, needsOnboarding=false, onboardingJustCompleted=true).
  //    /chat reads these to decide whether to re-mount the tour; without
  //    the state flip it would loop the tour on every visit.
  //    home_address on completeOnboarding maps to zip_code in the DB
  //    (legacy naming — see auth-context.tsx:825).
  if (buf.profile) {
    try {
      await opts.completeOnboarding({
        first_name: buf.profile.first_name,
        last_name: buf.profile.last_name,
        date_of_birth: buf.profile.date_of_birth,
        home_address: buf.profile.zip_code || buf.profile.home_address,
      });
      result.profile_saved = true;
    } catch (e) {
      result.errors.push(`completeOnboarding threw: ${(e as Error).message}`);
    }
  }

  // 2) Dependents. Primary dependent goes first so we can switchProfile
  //    to its id before creating silent ones (the silent-creation flow
  //    in the live tour uses fire-and-forget; we preserve that behavior
  //    but with await so errors get captured).
  const primary = buf.dependents.find((d) => d.is_primary_dependent);
  const secondaries = buf.dependents.filter((d) => !d.is_primary_dependent);
  const ordered = primary ? [primary, ...secondaries] : secondaries;
  for (const dep of ordered) {
    try {
      const body: Record<string, string> = {
        first_name: dep.first_name,
        last_name: dep.last_name || "",
        relationship: dep.relationship,
      };
      if (dep.label) body.label = dep.label;
      if (dep.date_of_birth) body.date_of_birth = dep.date_of_birth;
      if (dep.zip_code) body.zip_code = dep.zip_code;
      const res = await apiFetch("/profiles", {
        method: "POST",
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        result.errors.push(`dependent ${dep.first_name} POST ${res.status}`);
        continue;
      }
      const created = await res.json();
      const newId: string | null = created?.id || created?.profile_id || null;
      if (newId) {
        result.dependents_created++;
        if (dep.is_primary_dependent) {
          result.primary_dependent_id = newId;
        }
      }
    } catch (e) {
      result.errors.push(`dependent ${dep.first_name} threw: ${(e as Error).message}`);
    }
  }

  // 3) Refresh profiles so the sidebar sees the new ones, then switch
  //    active profile to the primary dependent. Downstream tour state
  //    (situation, meds, care plan) all gets associated with this
  //    dependent when the chat loads — same semantics as the authed
  //    tour path.
  try { await opts.refreshProfiles(); } catch {}
  if (result.primary_dependent_id) {
    try { await opts.switchProfile(result.primary_dependent_id); } catch (e) {
      result.errors.push(`switchProfile threw: ${(e as Error).message}`);
    }
  }

  // 4) Health data writes — condition, medications, care-plan todos,
  //    action todos. These parity with the writes advanceFromElenaPlan
  //    does in the authed tour path. Target profile: the primary
  //    dependent if one exists (since the tour's situation/meds/care
  //    plan was about them), else the primary user.
  //
  //    Get the active profile_id via /auth/me. A fresh profile POST
  //    created it, but we haven't refetched yet — going through /auth/me
  //    reads active_profile which switchProfile just updated (or the
  //    freshly-created primary profile if no dependent).
  let activeProfileId: string | null = null;
  try {
    const meRes = await apiFetch("/auth/me");
    if (meRes.ok) {
      const me = await meRes.json();
      activeProfileId = me?.profile_id || null;
    }
  } catch (e) {
    result.errors.push(`/auth/me threw: ${(e as Error).message}`);
  }

  if (activeProfileId) {
    // Conditions.
    for (const c of buf.conditions) {
      try {
        const body: Record<string, string> = { name: c.name };
        if (c.status) body.status = c.status;
        if (c.diagnosed_date) body.diagnosed_date = c.diagnosed_date;
        if (c.notes) body.notes = c.notes;
        const res = await apiFetch(`/profile/${activeProfileId}/conditions/add`, {
          method: "POST",
          body: JSON.stringify(body),
        });
        if (!res.ok) result.errors.push(`condition ${c.name} POST ${res.status}`);
      } catch (e) {
        result.errors.push(`condition ${c.name} threw: ${(e as Error).message}`);
      }
    }
    // Medications — fire in parallel like the authed path does.
    await Promise.all(
      buf.medications.map(async (m) => {
        try {
          const body: Record<string, string> = { name: m.name };
          if (m.indication) body.indication = m.indication;
          if (m.dosage_strength) body.dosage_strength = m.dosage_strength;
          if (m.frequency) body.frequency = m.frequency;
          const res = await apiFetch(`/profile/${activeProfileId}/medications/add`, {
            method: "POST",
            body: JSON.stringify(body),
          });
          if (!res.ok) result.errors.push(`med ${m.name} POST ${res.status}`);
        } catch (e) {
          result.errors.push(`med ${m.name} threw: ${(e as Error).message}`);
        }
      }),
    );
    // Todos — parallel.
    await Promise.all(
      buf.todos.map(async (t) => {
        try {
          const body: Record<string, string> = { title: t.title };
          if (t.subtitle) body.subtitle = t.subtitle;
          if (t.category) body.category = t.category;
          if (t.frequency) body.frequency = t.frequency;
          if (t.due_date) body.due_date = t.due_date;
          if (t.book_message) body.book_message = t.book_message;
          const res = await apiFetch("/todos", {
            method: "POST",
            body: JSON.stringify(body),
          });
          if (!res.ok) result.errors.push(`todo ${t.title} POST ${res.status}`);
        } catch (e) {
          result.errors.push(`todo ${t.title} threw: ${(e as Error).message}`);
        }
      }),
    );
  } else if (buf.conditions.length > 0 || buf.medications.length > 0 || buf.todos.length > 0) {
    result.errors.push(
      `health_data_skipped: no active_profile_id (conditions=${buf.conditions.length}, meds=${buf.medications.length}, todos=${buf.todos.length})`,
    );
  }

  // 5) Tour-resume handoff. Tour state was persisted with phase="elena-plan"
  //    when the user clicked Continue (since we short-circuited before
  //    the phase transition). Update the stored phase to "joyride" so
  //    /chat's tour mount resumes at the "This is your profile" spotlight
  //    — it orients the user before opening the profile walkthrough cards.
  //    The joyride's TOUR_END handler advances to phase="profile" with
  //    profileStep=0, so from the user's POV the flow is:
  //       (anon) elena-plan Continue → signup → (authed) /chat
  //       → "This is your profile" spotlight → Health / Visits / Insurance
  //       / Family cards → seed sends into chat.
  //    The static snapshot's "joyride → profile" fallback (in tourSnapshot
  //    useMemo) only applies when the controls instance can't survive the
  //    transition. Under Plan A the tour remounts on /chat, so the joyride
  //    instance is fresh and the phase effect starts it via controls.start().
  //
  //    Also preserve the seeded-actions key in sessionStorage so the
  //    tour's existing finishTour logic (end of profile walkthrough)
  //    writes localStorage.elena_pending_query at the *natural* moment
  //    — AFTER the user finishes the walkthrough cards. If we wrote
  //    the seed here instead, chat-area's auto-send effect would fire
  //    the seed while the walkthrough overlay was still up, producing
  //    an agent response underneath the tour cards. The authed flow's
  //    timing is "seed fires on finishTour" — we preserve that.
  if (typeof window !== "undefined") {
    try {
      const raw = sessionStorage.getItem("elena_tour_state");
      if (raw) {
        const state = JSON.parse(raw);
        state.phase = "joyride";
        state.profileStep = 0;
        sessionStorage.setItem("elena_tour_state", JSON.stringify(state));
      }
    } catch {}
    // Ensure finishTour (at the end of profile walkthrough) has an
    // elena_tour_seeded_actions payload to read. The tour's elena-plan
    // Continue handler wrote this already in the authed path; make sure
    // it's still there for anon path (it IS — advanceFromElenaPlan
    // writes the key before the anon short-circuit). Nothing else to
    // do here, documenting for clarity.
  }

  // Clear the tour buffer after a successful or partial flush — anything
  // that failed is recoverable via the profile popover, and keeping the
  // buffer around would replay on a later tour attempt. elena_tour_state
  // + elena_tour_seeded_actions stay (finishTour consumes them at the
  // end of the resumed profile walkthrough).
  clearTourBuffer();
  return result;
}
